from .base import *

DEBUG = False

ALLOWED_HOSTS = []

# This has to be set in every environment
MIDDLEWARE = DJANGO_MIDDLEWARE + THIRD_PARTY_MIDDLEWARE
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS