version: '3'

services:
  db:
    image: postgres
  web:
    environment:
      - DJANGO_ENV=dev
    build: .
    entrypoint: python3 project_name/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
